input:
  mechatronics_file: mechatronics.yaml           # default comes from hive.resources.mechatronics.mechatronics.csv
  road_network_file: null                       # default is to construct a Haversine road network
  geofence_file: null                           # default is to have no geofencing
  rate_structure_file: null                     # default is $0.00 for all services
  charging_price_file: null                     # default is $0.00 for any charging
  demand_forecast_file: null                    # default is no demand forecasting
sim:
  timestep_duration_seconds: 60                 # default is to advance time 1 minute between dispatcher updates
  sim_h3_resolution: 15                         # default is to store GeoIds at h3 resolution 15 (approx 1 meter hexes)
                                                # see https://github.com/uber/h3/blob/master/docs/core-library/restable.md
  sim_h3_search_resolution: 7                   # conduct bi-level search at h3 resolution 7
  request_cancel_time_seconds: 600              # requests are cancelled by default after 10 minutes of simulation wait time
  schedule_type: "time_range"                   # finds human-driver schedules in a CSV file with start + end time ranges
network:
  network_type: euclidean                       # default is to produce the Haversine Euclidean road newtork
  default_speed_kmph: 40.0                      # default Haversine network speeds are 40.0 kmph on each link
dispatcher:
  default_update_interval_seconds: 600          # 10 minutes
  matching_range_km_threshold: 20               # ignore matching requests when remaining range is less than 20km
  charging_range_km_threshold: 20               # ignore charging at stations when remaining range is greater than 20km plus the nearest station distance
  charging_range_km_soft_threshold: 50          # ignore charging at stations when remaining range is greater than 50km
  base_charging_range_km_threshold: 100         # ignore base charging at bases more than 100 km away
  ideal_fastcharge_soc_limit: 0.8               # fast charging can finish when 80% state-of-charge is reached
  max_search_radius_km: 100.0                   # when searching, ignore entities that are further than 100km away
  valid_dispatch_states:                        # allow agents to service a trip coming only from these vehicle states
    - idle
    - repositioning
  charging_search_type: nearest_shortest_queue  # "nearest_shortest_queue", or, "shortest_time_to_charge"
  idle_time_out_seconds: 1800                   # how long vehicles will idle before timing out, 30 minutes